-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 18:38:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql9613433
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql9613433
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql9613433` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `sql9613433` ;

-- -----------------------------------------------------
-- Table `sql9613433`.`anio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`anio` (
  `id_anio` VARCHAR(50) NOT NULL,
  `anio` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_anio`),
  UNIQUE INDEX `id_año_unique` (`id_anio` ASC) ,
  UNIQUE INDEX `año_unique` (`anio` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`asociaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`asociaciones` (
  `id_aso` VARCHAR(50) NOT NULL,
  `nom_asociacion` TEXT NULL DEFAULT NULL,
  `estado_aso` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_aso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`barrios` (
  `id_barrio` VARCHAR(50) NOT NULL,
  `nom_barrio` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_barrio`),
  UNIQUE INDEX `nom_barrio` (`nom_barrio` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`terrenos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`terrenos` (
  `id_terreno` VARCHAR(50) NOT NULL,
  `lim_norte` MEDIUMTEXT NULL DEFAULT NULL,
  `lim_sur` MEDIUMTEXT NULL DEFAULT NULL,
  `lim_este` MEDIUMTEXT NULL DEFAULT NULL,
  `lim_oeste` MEDIUMTEXT NULL DEFAULT NULL,
  `norte` INT NULL DEFAULT '0',
  `sur` INT NULL DEFAULT '0',
  `este` INT NULL DEFAULT '0',
  `oeste` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_terreno`),
  UNIQUE INDEX `id_terreno_unique` (`id_terreno` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`nacionalidad` (
  `id_nacionalidad` VARCHAR(50) NOT NULL,
  `nacionalidad` VARCHAR(100) NULL DEFAULT NULL,
  `estado_nac` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_nacionalidad`),
  UNIQUE INDEX `nacionalidad_unique` (`nacionalidad` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`personas` (
  `id_persona` VARCHAR(50) NOT NULL,
  `id_nacionalidad` VARCHAR(50) NULL DEFAULT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `genero` TINYINT(1) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `celular_per` VARCHAR(10) NULL DEFAULT NULL,
  `titulo_academico` VARCHAR(10) NULL DEFAULT 'sr.',
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `cedula` (`cedula` ASC) ,
  INDEX `fk_rel_nacionalidad_person` (`id_nacionalidad` ASC) ,
  CONSTRAINT `fk_rel_nacionalidad_person`
    FOREIGN KEY (`id_nacionalidad`)
    REFERENCES `sql9613433`.`nacionalidad` (`id_nacionalidad`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`comuneros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`comuneros` (
  `id_comunero` VARCHAR(50) NOT NULL,
  `id_barrio` VARCHAR(50) NULL DEFAULT NULL,
  `id_aso` VARCHAR(50) NULL DEFAULT NULL,
  `id_persona` VARCHAR(50) NULL DEFAULT NULL,
  `calificado` TINYINT(1) NULL DEFAULT '0',
  `created_date` DATE NULL DEFAULT NULL,
  `created_time` TIME NULL DEFAULT NULL,
  `estado_com` TINYINT(1) NULL DEFAULT '1',
  `id_terreno` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_comunero`),
  INDEX `fk_rel_asociacion_comunero` (`id_aso` ASC) ,
  INDEX `fk_rel_barrio_comunero` (`id_barrio` ASC) ,
  INDEX `fk_rel_pers_comunero` (`id_persona` ASC) ,
  INDEX `fk_comuneros_terrenos1_idx` (`id_terreno` ASC) ,
  CONSTRAINT `fk_comuneros_terrenos1`
    FOREIGN KEY (`id_terreno`)
    REFERENCES `sql9613433`.`terrenos` (`id_terreno`),
  CONSTRAINT `fk_rel_asociacion_comunero`
    FOREIGN KEY (`id_aso`)
    REFERENCES `sql9613433`.`asociaciones` (`id_aso`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rel_barrio_comunero`
    FOREIGN KEY (`id_barrio`)
    REFERENCES `sql9613433`.`barrios` (`id_barrio`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rel_pers_comunero`
    FOREIGN KEY (`id_persona`)
    REFERENCES `sql9613433`.`personas` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`tipo_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`tipo_documentos` (
  `id_tipo_doc` VARCHAR(50) NOT NULL,
  `tipo_doc` LONGTEXT NOT NULL,
  `estado_doc` TINYINT(1) NULL DEFAULT '1',
  `alias` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`comuneros_tipos_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`comuneros_tipos_doc` (
  `id_comunero` VARCHAR(50) NOT NULL,
  `id_tipo_doc` VARCHAR(50) NOT NULL,
  `documento` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_comunero`, `id_tipo_doc`),
  INDEX `fk_comuneros_has_tipo_documentos_tipo_documentos1_idx` (`id_tipo_doc` ASC) ,
  INDEX `fk_comuneros_has_tipo_documentos_comuneros1_idx` (`id_comunero` ASC) ,
  CONSTRAINT `fk_comuneros_has_tipo_documentos_comuneros1`
    FOREIGN KEY (`id_comunero`)
    REFERENCES `sql9613433`.`comuneros` (`id_comunero`),
  CONSTRAINT `fk_comuneros_has_tipo_documentos_tipo_documentos1`
    FOREIGN KEY (`id_tipo_doc`)
    REFERENCES `sql9613433`.`tipo_documentos` (`id_tipo_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`cuota_anual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`cuota_anual` (
  `id_cuota` VARCHAR(50) NOT NULL,
  `nom_cuota` VARCHAR(100) NOT NULL,
  `valor_cuota` FLOAT NOT NULL,
  `estado_cuota` TINYINT(1) NOT NULL DEFAULT '1',
  `id_anio` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cuota`, `id_anio`),
  INDEX `fk_cuota_anual_table11_idx` (`id_anio` ASC) ,
  CONSTRAINT `fk_cuota_anual_table11`
    FOREIGN KEY (`id_anio`)
    REFERENCES `sql9613433`.`anio` (`id_anio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`forma_pago` (
  `id_forma_pago` VARCHAR(50) NOT NULL,
  `forma_pago` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_forma_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`facturas` (
  `id_factura` VARCHAR(50) NOT NULL,
  `id_comunero` VARCHAR(50) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `subtotal_fac` FLOAT NOT NULL,
  `total_fac` FLOAT NOT NULL,
  `descrip_fac` VARCHAR(100) NULL DEFAULT NULL,
  `estado_fac` TINYINT(1) NULL DEFAULT '1',
  `id_forma_pago` VARCHAR(50) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_factura`),
  INDEX `fk_rel_comunero_fact` (`id_comunero` ASC) ,
  INDEX `fk_facturas_forma_pago1_idx` (`id_forma_pago` ASC) ,
  CONSTRAINT `fk_facturas_forma_pago1`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `sql9613433`.`forma_pago` (`id_forma_pago`),
  CONSTRAINT `fk_rel_comunero_fact`
    FOREIGN KEY (`id_comunero`)
    REFERENCES `sql9613433`.`comuneros` (`id_comunero`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`cuotas_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`cuotas_factura` (
  `id_factura` VARCHAR(50) NOT NULL,
  `id_cuota` VARCHAR(50) NOT NULL,
  `id_anio` VARCHAR(50) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_factura`, `id_cuota`, `id_anio`),
  INDEX `fk_facturas_has_cuota_anual_cuota_anual1_idx` (`id_cuota` ASC, `id_anio` ASC) ,
  INDEX `fk_facturas_has_cuota_anual_facturas1_idx` (`id_factura` ASC) ,
  CONSTRAINT `fk_facturas_has_cuota_anual_cuota_anual1`
    FOREIGN KEY (`id_cuota` , `id_anio`)
    REFERENCES `sql9613433`.`cuota_anual` (`id_cuota` , `id_anio`),
  CONSTRAINT `fk_facturas_has_cuota_anual_facturas1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `sql9613433`.`facturas` (`id_factura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`requisitos` (
  `id_req` VARCHAR(50) NOT NULL,
  `requisito` VARCHAR(255) NOT NULL,
  `observacion` VARCHAR(255) NULL DEFAULT NULL,
  `req_estado` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_req`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`requisito_apr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`requisito_apr` (
  `id_req_ap` VARCHAR(50) NOT NULL,
  `fecha_ap` DATE NOT NULL,
  `observacion` VARCHAR(150) NULL DEFAULT 'ninguna',
  `id_persona` VARCHAR(50) NOT NULL,
  `id_req` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_req_ap`, `id_req`),
  INDEX `fk_requisito_apr_personas1_idx` (`id_persona` ASC) ,

  INDEX `fk_requisito_apr_requisitos1_idx` (`id_req` ASC) ,
  CONSTRAINT `fk_requisito_apr_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `sql9613433`.`personas` (`id_persona`),
  CONSTRAINT `fk_requisito_apr_requisitos1`
    FOREIGN KEY (`id_req`)
    REFERENCES `sql9613433`.`requisitos` (`id_req`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`rol_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`rol_user` (
  `id_rol` VARCHAR(50) NOT NULL,
  `nom_rol` VARCHAR(50) NOT NULL,
  `estado_rol` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sql9613433`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql9613433`.`usuarios` (
  `id_usuario` VARCHAR(50) NOT NULL,
  `id_comunero` VARCHAR(50) NULL DEFAULT NULL,
  `id_rol` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at_date` DATE NOT NULL,
  `created_at_time` TIME NOT NULL,
  `nom_user` VARCHAR(12) NOT NULL,
  `pass_user` TEXT NOT NULL,
  `estado_user` TINYINT(1) NULL DEFAULT '1',
  `img` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) ,
  INDEX `fk_rel_comunero_usuario` (`id_comunero` ASC) ,
  INDEX `fk_rel_user_rol` (`id_rol` ASC) ,
  CONSTRAINT `fk_rel_comunero_usuario`
    FOREIGN KEY (`id_comunero`)
    REFERENCES `sql9613433`.`comuneros` (`id_comunero`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rel_user_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sql9613433`.`rol_user` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
